In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [1]:
def mat_operations(matrix):
    if matrix.size > 0:
        is_ones = True if np.all((matrix == 1)) else False 
        is_square = True if matrix.shape[0] == matrix.shape[1] else False ##checks if the matrix is a square
        is_zero = True if np.all((matrix == 0)) else False ##checks if the matrix is equals to 0
        is_identity = True if matrix.shape[0] == matrix.shape[1] and np.allclose(matrix, np.eye(matrix.shape[0])) else False
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
        print (f' is the matrix a ones matrix? {is_ones}\n')
        print (f' is the matrix a zero matrix? {is_zero} \n')
        print (f' is the matrix an identity matrix? {is_identity} \n' )
    else:
        print('Matrix is Null')## Function area

In [ ]:
G = np.array([
    [4,6,2],
    [3,1,5],
    [8,7,6]])

A = np.array([
    [2,3,1,4],
    [0,3,2,4],
    [1,0,3,2],
    [1,2,3,4]])

T = np.array([
    [4,5,2],
    [2,1,2],
    [3,2,1],
    [5,6,0]])
C = np.array([
    [2,3,1],
    [0,5,4],
    [9,9,9],
    [2,4,3]])
H = np.array([
    [3,0,2,1,5],
    [3,2,4,4,6],
    [1,2,3,5,7],
    [3,4,5,1,0]
    
])

    ## Matrix declarations

In [ ]:
mat_operations(G)

Matrix:
[[4 6 2]
 [3 1 5]
 [8 7 6]]

Shape:	(3, 3)
Rank:	2
Is Square: True

 is the matrix a ones matrix? False

 is the matrix a zero matrix? False 

 is the matrix an identity matrix? False 



In [ ]:
mat_operations(A)

Matrix:
[[2 3 1 4]
 [0 3 2 4]
 [1 0 3 2]
 [1 2 3 4]]

Shape:	(4, 4)
Rank:	2
Is Square: True

 is the matrix a ones matrix? False

 is the matrix a zero matrix? False 

 is the matrix an identity matrix? False 



In [ ]:
mat_operations(T)

Matrix:
[[4 5 2]
 [2 1 2]
 [3 2 1]
 [5 6 0]]

Shape:	(4, 3)
Rank:	2
Is Square: False

 is the matrix a ones matrix? False

 is the matrix a zero matrix? False 

 is the matrix an identity matrix? False 



In [ ]:
mat_operations(C)

Matrix:
[[2 3 1]
 [0 5 4]
 [9 9 9]
 [2 4 3]]

Shape:	(4, 3)
Rank:	2
Is Square: False

 is the matrix a ones matrix? False

 is the matrix a zero matrix? False 

 is the matrix an identity matrix? False 



In [ ]:
mat_operations(H)

Matrix:
[[3 0 2 1 5]
 [3 2 4 4 6]
 [1 2 3 5 7]
 [3 4 5 1 0]]

Shape:	(4, 5)
Rank:	2
Is Square: False

 is the matrix a ones matrix? False

 is the matrix a zero matrix? False 

 is the matrix an identity matrix? False 

