In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [5]:
def mat_operations(C,A):
    alpha = 10**-10
    if np.isscalar(C):
        print("The first parameter is a scalar")
    else:
        print(f'1st matrix:\n {C}\n'
        f'The shape of the 1st matrix is: {C.shape}\n'
        f'The size of the 1st matrix is: {np.product(C.shape)}\n'
        f'The rank of the 1st matrix is: {C.ndim}')
        if C.size > 0:
            is_ones = True if np.all((C == 1)) else False ##checks if the elements are 1 
            is_zero = True if np.all((C == 0)) else False ## checks if the elements are 0 
            is_square = True if C.shape[0] == C.shape[1] else False ##checks if the elements are square
            is_identity = True if C.shape[0] == C.shape[1] and np.allclose(C, np.eye(C.shape[0])) else False 
            ## checks if the matrix is a square, identity, ones or zero/s
            print(f'Is the matrix a ones matrix?: {is_ones}\n'
            f'Is the matrix a zero matrix?: {is_zero}\n'
            f'Is the matrix a square?: {is_square}\n'
            f'Is the matrix an identity matrix?: {is_identity}\n\n'
            )
        else:
            print("The Matrix is Null or Empty")
    
    if np.isscalar(A):
        print("The first parameter is a scalar")
    else:
        print(f'1st matrix:\n {A}\n'
        f'The shape of the 1st matrix is: {A.shape}\n'
        f'The size of the 1st matrix is: {np.product(A.shape)}\n'
        f'The rank of the 1st matrix is: {A.ndim}')
        if A.size > 0:
            is_ones = True if np.all((A == 1)) else False ##checks if the elements are 1 
            is_zero = True if np.all((A == 0)) else False ## checks if the elements are 0 
            is_square = True if A.shape[0] == A.shape[1] else False ##checks if the elements are square
            is_identity = True if A.shape[0] == A.shape[1] and np.allclose(A, np.eye(A.shape[0])) else False 
            ## checks if the matrix is a square, identity, ones or zero/s
            print(f'Is the matrix a ones matrix?: {is_ones}\n'
            f'Is the matrix a zero matrix?: {is_zero}\n'
            f'Is the matrix a square?: {is_square}\n'
            f'Is the matrix an identity matrix?: {is_identity}\n\n'
            )
        else:
            print("The Matrix is Null or Empty")
            
    if np.isscalar(C) == False and np.isscalar(A) == False:
        if (C.shape == A.shape):
            print(f'The sum of the matrix/matrices are: \n{np.sum(np.add(C,A))}\n'
                f'\nThe difference of the matrix/matrices are: \n{np.diff(np.subtract(C,A))}\n'
                f'\nThe element-wise multiplication of the matrices is: \n{np.multiply(C,A)}\n'
                f'\nThe element-wise division of the matrices is: \n{np.divide(C,A+alpha)}\n')
        else:
            print("The matrix/matrices are not viable for operation\n")
    else:
        print("The parameters are not viable for matrix operation\n")

In [6]:
G = np.array([
    [4,6,2],
    [3,1,5],
    [8,7,6]])

A = np.array([
    [2,3,1,4],
    [0,3,2,4],
    [1,0,3,2],
    [1,2,3,4]])

T = np.array([
    [4,5,2],
    [2,1,2],
    [3,2,1],
    [5,6,0]])
C = np.array([
    [2,3,1],
    [0,5,4],
    [9,9,9],
    [2,4,3]])
H = np.array([
    [3,0,2,1,5],
    [3,2,4,4,6],
    [1,2,3,5,7],
    [3,4,5,1,0]
    
])

    ## Matrix declarations

In [8]:
print("matrices pair 1:\n")
mat_operations(G,A)
print("matrices pair 2:\n")
mat_operations(T,C)
print("matrices pair 3:\n")
mat_operations(H,G)

matrices pair 1:

1st matrix:
 [[4 6 2]
 [3 1 5]
 [8 7 6]]
The shape of the 1st matrix is: (3, 3)
The size of the 1st matrix is: 9
The rank of the 1st matrix is: 2
Is the matrix a ones matrix?: False
Is the matrix a zero matrix?: False
Is the matrix a square?: True
Is the matrix an identity matrix?: False


1st matrix:
 [[2 3 1 4]
 [0 3 2 4]
 [1 0 3 2]
 [1 2 3 4]]
The shape of the 1st matrix is: (4, 4)
The size of the 1st matrix is: 16
The rank of the 1st matrix is: 2
Is the matrix a ones matrix?: False
Is the matrix a zero matrix?: False
Is the matrix a square?: True
Is the matrix an identity matrix?: False


The matrix/matrices are not viable for operation

matrices pair 2:

1st matrix:
 [[4 5 2]
 [2 1 2]
 [3 2 1]
 [5 6 0]]
The shape of the 1st matrix is: (4, 3)
The size of the 1st matrix is: 12
The rank of the 1st matrix is: 2
Is the matrix a ones matrix?: False
Is the matrix a zero matrix?: False
Is the matrix a square?: False
Is the matrix an identity matrix?: False


1st matrix:
